defmodule AshPersistence.SqliteRepo.Migrations.DurableSqliteBackend do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:durable_steps, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :undo_payload, :map
      add :compensation_payload, :map
      add :halt_payload, :map
      add :error, :text
      add :output, :map
      add :inputs, :map, default: %{}
      add :mode, :text, null: false
      add :attempt, :bigint, null: false
      add :status, :text, null: false
      add :step_hash, :bigint
      add :step_impl, :text
      add :step_name, :text, null: false
      add :run_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:durable_steps, [:run_id, :step_name],
             name: "durable_steps_unique_run_step_index"
           )

    create table(:durable_runs, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :attempt, :bigint, null: false
      add :halt_reason, :map
      add :error, :text
      add :result, :map
      add :persisted_context, :map, default: %{}
      add :inputs, :map, default: %{}
      add :status, :text, null: false
      add :reactor_module, :text, null: false
      add :reactor_hash, :bigint, null: false
      add :run_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:durable_runs, [:run_id], name: "durable_runs_unique_run_id_index")

    create table(:durable_events, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :payload, :map, default: %{}
      add :event_type, :text, null: false
      add :step_name, :text, null: false
      add :run_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:durable_events)

    drop_if_exists unique_index(:durable_runs, [:run_id],
                     name: "durable_runs_unique_run_id_index"
                   )

    drop table(:durable_runs)

    drop_if_exists unique_index(:durable_steps, [:run_id, :step_name],
                     name: "durable_steps_unique_run_step_index"
                   )

    drop table(:durable_steps)
  end
end